// <auto-generated />
using System;
using EntityFrameworkCore.Jet.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RRFFilesManager.DataAccess;

namespace RRFFilesManager.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210201014512_Initial_EFCore")]
    partial class Initial_EFCore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RRFFilesManager.Abstractions.Archive", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("longchar");

                    b.Property<string>("Path")
                        .HasColumnType("longchar");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("FileId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Archives");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("longchar");

                    b.Property<string>("City")
                        .HasColumnType("longchar");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("longchar");

                    b.Property<string>("EmailToText")
                        .HasColumnType("longchar");

                    b.Property<string>("FirstName")
                        .HasColumnType("longchar");

                    b.Property<string>("HomeNumber")
                        .HasColumnType("longchar");

                    b.Property<string>("LastName")
                        .HasColumnType("longchar");

                    b.Property<string>("MobileCarrier")
                        .HasColumnType("longchar");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("longchar");

                    b.Property<string>("OtherNotes")
                        .HasColumnType("longchar");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("longbinary");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longchar");

                    b.Property<int?>("ProvinceID")
                        .HasColumnType("integer");

                    b.Property<string>("Salutation")
                        .HasColumnType("longchar");

                    b.Property<string>("SuiteApt")
                        .HasColumnType("longchar");

                    b.Property<string>("WorkNumber")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.HasIndex("ProvinceID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasColumnType("longchar");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longchar");

                    b.Property<string>("City")
                        .HasColumnType("longchar");

                    b.Property<string>("Description")
                        .HasColumnType("longchar");

                    b.Property<string>("Email")
                        .HasColumnType("longchar");

                    b.Property<string>("Extension")
                        .HasColumnType("longchar");

                    b.Property<string>("Fax")
                        .HasColumnType("longchar");

                    b.Property<string>("Memo")
                        .HasColumnType("longchar");

                    b.Property<string>("Phone")
                        .HasColumnType("longchar");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longchar");

                    b.Property<int?>("ProvinceID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ProvinceID");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Contact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasColumnType("longchar");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("longchar");

                    b.Property<string>("Cell")
                        .HasColumnType("longchar");

                    b.Property<string>("City")
                        .HasColumnType("longchar");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("integer");

                    b.Property<int?>("Contact1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Contact2Id")
                        .HasColumnType("integer");

                    b.Property<string>("Date")
                        .HasColumnType("longchar");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("DirectExtension")
                        .HasColumnType("longchar");

                    b.Property<string>("DirectNumber")
                        .HasColumnType("longchar");

                    b.Property<string>("Email")
                        .HasColumnType("longchar");

                    b.Property<string>("Email2")
                        .HasColumnType("longchar");

                    b.Property<string>("EmailToText")
                        .HasColumnType("longchar");

                    b.Property<string>("Fax")
                        .HasColumnType("longchar");

                    b.Property<string>("FirstLenguage")
                        .HasColumnType("longchar");

                    b.Property<string>("FirstName")
                        .HasColumnType("longchar");

                    b.Property<int?>("GroupID")
                        .HasColumnType("integer");

                    b.Property<string>("HealthCard")
                        .HasColumnType("longchar");

                    b.Property<string>("HomeNumber")
                        .HasColumnType("longchar");

                    b.Property<string>("JobTitle")
                        .HasColumnType("longchar");

                    b.Property<string>("LastName")
                        .HasColumnType("longchar");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("longchar");

                    b.Property<string>("Link")
                        .HasColumnType("longchar");

                    b.Property<string>("MobileCarrier")
                        .HasColumnType("longchar");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("longchar");

                    b.Property<string>("Notes")
                        .HasColumnType("longchar");

                    b.Property<string>("OfficeExtension")
                        .HasColumnType("longchar");

                    b.Property<string>("OfficeNumber")
                        .HasColumnType("longchar");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("longbinary");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longchar");

                    b.Property<string>("Prefix")
                        .HasColumnType("longchar");

                    b.Property<int?>("ProvinceID")
                        .HasColumnType("integer");

                    b.Property<string>("Relationship")
                        .HasColumnType("longchar");

                    b.Property<string>("SIN")
                        .HasColumnType("longchar");

                    b.Property<string>("Salutation")
                        .HasColumnType("longchar");

                    b.Property<string>("Suffix")
                        .HasColumnType("longchar");

                    b.Property<string>("TeamMember")
                        .HasColumnType("longchar");

                    b.Property<string>("Website")
                        .HasColumnType("longchar");

                    b.Property<string>("WorkNumber")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("Contact1Id");

                    b.HasIndex("Contact2Id");

                    b.HasIndex("GroupID");

                    b.HasIndex("ProvinceID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.DisabilityInsuranceCompany", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.ToTable("DisabilityInsuranceCompanies");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.File", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("longchar");

                    b.Property<int?>("ClientID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOFLoss")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateOfCall")
                        .HasColumnType("datetime");

                    b.Property<int?>("FileLawyerID")
                        .HasColumnType("integer");

                    b.Property<int>("FileNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("HowHearID")
                        .HasColumnType("integer");

                    b.Property<string>("LimitationPeriod")
                        .HasColumnType("longchar");

                    b.Property<int?>("MatterSubTypeID")
                        .HasColumnType("integer");

                    b.Property<int?>("MatterTypeID")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponsibleLawyerID")
                        .HasColumnType("integer");

                    b.Property<int?>("StaffInterviewerID")
                        .HasColumnType("integer");

                    b.Property<string>("StatutoryNotice")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("FileLawyerID");

                    b.HasIndex("HowHearID");

                    b.HasIndex("MatterSubTypeID");

                    b.HasIndex("MatterTypeID");

                    b.HasIndex("ResponsibleLawyerID");

                    b.HasIndex("StaffInterviewerID");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Group", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.HearAboutUs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.ToTable("HearAboutUs");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Intake", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccBenAdjuster")
                        .HasColumnType("longchar");

                    b.Property<string>("AccBenClaimNumber")
                        .HasColumnType("longchar");

                    b.Property<string>("AccBenDriverPassenger")
                        .HasColumnType("longchar");

                    b.Property<string>("AccBenInsuranceCompany")
                        .HasColumnType("longchar");

                    b.Property<string>("AccBenNotes")
                        .HasColumnType("longchar");

                    b.Property<string>("AccBenOCF1")
                        .HasColumnType("longchar");

                    b.Property<string>("AccBenOCF2")
                        .HasColumnType("longchar");

                    b.Property<string>("AccBenOCF3")
                        .HasColumnType("longchar");

                    b.Property<string>("AccBenPolicyNumber")
                        .HasColumnType("longchar");

                    b.Property<string>("AccBenRegisOwnerName")
                        .HasColumnType("longchar");

                    b.Property<string>("AccBenReplacBenef")
                        .HasColumnType("longchar");

                    b.Property<string>("AccBenWereRegisOwner")
                        .HasColumnType("longchar");

                    b.Property<string>("DamHeadInjuries")
                        .HasColumnType("longchar");

                    b.Property<string>("DamHitVehicleConcrete")
                        .HasColumnType("longchar");

                    b.Property<string>("DamLowerBodyInjuries")
                        .HasColumnType("longchar");

                    b.Property<string>("DamNotes")
                        .HasColumnType("longchar");

                    b.Property<string>("DamPreAccident")
                        .HasColumnType("longchar");

                    b.Property<string>("DamPreIllness")
                        .HasColumnType("longchar");

                    b.Property<string>("DamPrescribed")
                        .HasColumnType("longchar");

                    b.Property<string>("DamPsychologicalEffect")
                        .HasColumnType("longchar");

                    b.Property<string>("DamUpperBodyInjuries")
                        .HasColumnType("longchar");

                    b.Property<string>("DamWereSeeingDoctor")
                        .HasColumnType("longchar");

                    b.Property<string>("EILCollecInsurance")
                        .HasColumnType("longchar");

                    b.Property<string>("EILEmployed4Weeks")
                        .HasColumnType("longchar");

                    b.Property<string>("EILEmployed52Weeks")
                        .HasColumnType("longchar");

                    b.Property<string>("EILEmployeeGrossEarning")
                        .HasColumnType("longchar");

                    b.Property<string>("EILExplainJob")
                        .HasColumnType("longchar");

                    b.Property<string>("EILHowLongBusiness")
                        .HasColumnType("longchar");

                    b.Property<string>("EILHowLongEmployee")
                        .HasColumnType("longchar");

                    b.Property<string>("EILJobTitle")
                        .HasColumnType("longchar");

                    b.Property<string>("EILNotes")
                        .HasColumnType("longchar");

                    b.Property<string>("EILSelfBusinessName")
                        .HasColumnType("longchar");

                    b.Property<string>("EILSelfGrossEarning")
                        .HasColumnType("longchar");

                    b.Property<string>("EILT4Company")
                        .HasColumnType("longchar");

                    b.Property<string>("EILT4Employee")
                        .HasColumnType("longchar");

                    b.Property<string>("EILWereEmployed")
                        .HasColumnType("longchar");

                    b.Property<string>("EILWereSelfEmployed")
                        .HasColumnType("longchar");

                    b.Property<string>("ExcelFile")
                        .HasColumnType("longchar");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<bool>("Hold")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LiaDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LiaDriverName")
                        .HasColumnType("longchar");

                    b.Property<string>("LiaEstimDamage")
                        .HasColumnType("longchar");

                    b.Property<string>("LiaExplain")
                        .HasColumnType("longchar");

                    b.Property<string>("LiaFaultPerson")
                        .HasColumnType("longchar");

                    b.Property<string>("LiaHaveCopy")
                        .HasColumnType("longchar");

                    b.Property<string>("LiaHavePhotos")
                        .HasColumnType("longchar");

                    b.Property<string>("LiaInsuranceCo")
                        .HasColumnType("longchar");

                    b.Property<bool>("LiaMVCExchange")
                        .HasColumnType("smallint");

                    b.Property<bool>("LiaMVR")
                        .HasColumnType("smallint");

                    b.Property<string>("LiaMunicipality")
                        .HasColumnType("longchar");

                    b.Property<string>("LiaNotes")
                        .HasColumnType("longchar");

                    b.Property<string>("LiaNotifiedMunicipality")
                        .HasColumnType("longchar");

                    b.Property<bool>("LiaOtherDoc")
                        .HasColumnType("smallint");

                    b.Property<string>("LiaOwnNegligence")
                        .HasColumnType("longchar");

                    b.Property<string>("LiaOwnerName")
                        .HasColumnType("longchar");

                    b.Property<bool>("LiaReportCollision")
                        .HasColumnType("smallint");

                    b.Property<string>("LiaWhereAccident")
                        .HasColumnType("longchar");

                    b.Property<string>("LiaYourFault")
                        .HasColumnType("longchar");

                    b.Property<string>("Notes")
                        .HasColumnType("longchar");

                    b.Property<string>("PolApplicationForCPP")
                        .HasColumnType("longchar");

                    b.Property<string>("PolCPPApproved")
                        .HasColumnType("longchar");

                    b.Property<string>("PolCPPOwnOrCompany")
                        .HasColumnType("longchar");

                    b.Property<int?>("PolCompanyDeniedBenefitsID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PolDateLastDayLTD")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("PolDateLostBenefits")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("PolDateStartedCollLTD")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("PolDateSubmittedLTD")
                        .HasColumnType("datetime");

                    b.Property<string>("PolDeniedSTPorLTD")
                        .HasColumnType("longchar");

                    b.Property<string>("PolFirstTimeLTDApproved")
                        .HasColumnType("longchar");

                    b.Property<string>("PolHowMuchBeingPaid")
                        .HasColumnType("longchar");

                    b.Property<string>("PolLTDPrivateOrEmployerGroup")
                        .HasColumnType("longchar");

                    b.Property<string>("PolOtherNotes")
                        .HasColumnType("longchar");

                    b.Property<string>("PolReasonTerminateLTD")
                        .HasColumnType("longchar");

                    b.Property<string>("PolSickBenefits")
                        .HasColumnType("longchar");

                    b.Property<string>("PolWhoPaidBenefits")
                        .HasColumnType("longchar");

                    b.Property<string>("WordFile")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("PolCompanyDeniedBenefitsID");

                    b.ToTable("Intakes");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Lawyer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("longchar");

                    b.Property<int?>("NumberID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Lawyers");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.MatterSubType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("longchar");

                    b.Property<int?>("MatterTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("StatutoryNotice")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.HasIndex("MatterTypeID");

                    b.ToTable("MatterSubTypes");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.MatterType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.ToTable("MatterTypes");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.MobileCarrier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("longchar");

                    b.Property<string>("Gate")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.ToTable("MobileCarriers");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GroupID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.HasIndex("GroupID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Province", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Template", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Jet:ValueGenerationStrategy", JetValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("longchar");

                    b.Property<int?>("MatterTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateName")
                        .HasColumnType("longchar");

                    b.Property<string>("TemplatePath")
                        .HasColumnType("longchar");

                    b.Property<string>("TypeOfTemplate")
                        .HasColumnType("longchar");

                    b.HasKey("ID");

                    b.HasIndex("MatterTypeID");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Archive", b =>
                {
                    b.HasOne("RRFFilesManager.Abstractions.File", "File")
                        .WithMany("Archives")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRFFilesManager.Abstractions.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Client", b =>
                {
                    b.HasOne("RRFFilesManager.Abstractions.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceID");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Company", b =>
                {
                    b.HasOne("RRFFilesManager.Abstractions.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceID");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Contact", b =>
                {
                    b.HasOne("RRFFilesManager.Abstractions.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID");

                    b.HasOne("RRFFilesManager.Abstractions.Contact", "Contact1")
                        .WithMany()
                        .HasForeignKey("Contact1Id");

                    b.HasOne("RRFFilesManager.Abstractions.Contact", "Contact2")
                        .WithMany()
                        .HasForeignKey("Contact2Id");

                    b.HasOne("RRFFilesManager.Abstractions.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupID");

                    b.HasOne("RRFFilesManager.Abstractions.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceID");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.File", b =>
                {
                    b.HasOne("RRFFilesManager.Abstractions.Contact", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID");

                    b.HasOne("RRFFilesManager.Abstractions.Lawyer", "FileLawyer")
                        .WithMany()
                        .HasForeignKey("FileLawyerID");

                    b.HasOne("RRFFilesManager.Abstractions.HearAboutUs", "HowHear")
                        .WithMany()
                        .HasForeignKey("HowHearID");

                    b.HasOne("RRFFilesManager.Abstractions.MatterSubType", "MatterSubType")
                        .WithMany()
                        .HasForeignKey("MatterSubTypeID");

                    b.HasOne("RRFFilesManager.Abstractions.MatterType", "MatterType")
                        .WithMany()
                        .HasForeignKey("MatterTypeID");

                    b.HasOne("RRFFilesManager.Abstractions.Lawyer", "ResponsibleLawyer")
                        .WithMany()
                        .HasForeignKey("ResponsibleLawyerID");

                    b.HasOne("RRFFilesManager.Abstractions.Lawyer", "StaffInterviewer")
                        .WithMany()
                        .HasForeignKey("StaffInterviewerID");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Intake", b =>
                {
                    b.HasOne("RRFFilesManager.Abstractions.File", "File")
                        .WithOne("Intake")
                        .HasForeignKey("RRFFilesManager.Abstractions.Intake", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRFFilesManager.Abstractions.DisabilityInsuranceCompany", "PolCompanyDeniedBenefits")
                        .WithMany()
                        .HasForeignKey("PolCompanyDeniedBenefitsID");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.MatterSubType", b =>
                {
                    b.HasOne("RRFFilesManager.Abstractions.MatterType", "MatterType")
                        .WithMany()
                        .HasForeignKey("MatterTypeID");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Position", b =>
                {
                    b.HasOne("RRFFilesManager.Abstractions.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupID");
                });

            modelBuilder.Entity("RRFFilesManager.Abstractions.Template", b =>
                {
                    b.HasOne("RRFFilesManager.Abstractions.MatterType", "MatterType")
                        .WithMany()
                        .HasForeignKey("MatterTypeID");
                });
#pragma warning restore 612, 618
        }
    }
}
